// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// moewishart_cpp
Rcpp::List moewishart_cpp(Rcpp::List S_list, int K, int niter, int burnin, int thin, Rcpp::Nullable<Rcpp::NumericVector> alpha_in, Rcpp::Nullable<double> nu0_in, Rcpp::Nullable<Rcpp::NumericMatrix> Psi0_in, Rcpp::Nullable<Rcpp::NumericVector> init_nu_in, bool marginal_z, bool sample_nu, double nu_prior_a, double nu_prior_b, double mh_sigma, bool verbose);
RcppExport SEXP _moewishart_moewishart_cpp(SEXP S_listSEXP, SEXP KSEXP, SEXP niterSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP alpha_inSEXP, SEXP nu0_inSEXP, SEXP Psi0_inSEXP, SEXP init_nu_inSEXP, SEXP marginal_zSEXP, SEXP sample_nuSEXP, SEXP nu_prior_aSEXP, SEXP nu_prior_bSEXP, SEXP mh_sigmaSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type S_list(S_listSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type alpha_in(alpha_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type nu0_in(nu0_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type Psi0_in(Psi0_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type init_nu_in(init_nu_inSEXP);
    Rcpp::traits::input_parameter< bool >::type marginal_z(marginal_zSEXP);
    Rcpp::traits::input_parameter< bool >::type sample_nu(sample_nuSEXP);
    Rcpp::traits::input_parameter< double >::type nu_prior_a(nu_prior_aSEXP);
    Rcpp::traits::input_parameter< double >::type nu_prior_b(nu_prior_bSEXP);
    Rcpp::traits::input_parameter< double >::type mh_sigma(mh_sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(moewishart_cpp(S_list, K, niter, burnin, thin, alpha_in, nu0_in, Psi0_in, init_nu_in, marginal_z, sample_nu, nu_prior_a, nu_prior_b, mh_sigma, verbose));
    return rcpp_result_gen;
END_RCPP
}
// moewishart_em_cpp
Rcpp::List moewishart_em_cpp(Rcpp::List S_list, int K, Rcpp::Nullable< Rcpp::NumericVector > nu_in, int max_em, int max_nr, double tol_em, bool verbose);
RcppExport SEXP _moewishart_moewishart_em_cpp(SEXP S_listSEXP, SEXP KSEXP, SEXP nu_inSEXP, SEXP max_emSEXP, SEXP max_nrSEXP, SEXP tol_emSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type S_list(S_listSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable< Rcpp::NumericVector > >::type nu_in(nu_inSEXP);
    Rcpp::traits::input_parameter< int >::type max_em(max_emSEXP);
    Rcpp::traits::input_parameter< int >::type max_nr(max_nrSEXP);
    Rcpp::traits::input_parameter< double >::type tol_em(tol_emSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(moewishart_em_cpp(S_list, K, nu_in, max_em, max_nr, tol_em, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_moewishart_moewishart_cpp", (DL_FUNC) &_moewishart_moewishart_cpp, 15},
    {"_moewishart_moewishart_em_cpp", (DL_FUNC) &_moewishart_moewishart_em_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_moewishart(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
