# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Main function implemented in C++
#'
#' @name moewishart_cpp TBA
#'
#' @param S_list TBA
#' @param K TBA
#' @param niter TBA
#' @param burnin TBA
#' @param thin TBA
#' @param alpha_in TBA
#' @param nu0_in TBA
#' @param Psi0_in TBA
#' @param init_nu_in TBA
#' @param marginal_z TBA
#' @param sample_nu TBA
#' @param nu_prior_a TBA
#' @param nu_prior_b TBA
#' @param mh_sigma TBA
#' @param verbose TBA
#'
moewishart_cpp <- function(S_list, K, niter = 3000L, burnin = 1000L, thin = 1L, alpha_in = NULL, nu0_in = NULL, Psi0_in = NULL, init_nu_in = NULL, marginal_z = TRUE, sample_nu = TRUE, nu_prior_a = 2.0, nu_prior_b = 0.1, mh_sigma = 0.1, verbose = TRUE) {
    .Call(`_moewishart_moewishart_cpp`, S_list, K, niter, burnin, thin, alpha_in, nu0_in, Psi0_in, init_nu_in, marginal_z, sample_nu, nu_prior_a, nu_prior_b, mh_sigma, verbose)
}

#' EM for mixture of Wishart distributions with automatic nu_k estimation
#'
#' @name moewishart_em_cpp
NULL

#' @param S_list  list of n symmetric positive definite p x p matrices
#' @param K       number of components
#' @param nu_in   scalar or vector length K (initial nu). If NULL, defaults to p+2 per component
#' @param max_em  maximum EM iterations
#' @param max_nr  maximum Newton iterations for nu update
#' @param tol_em  relative tolerance on log-likelihood improvement
#' @param verbose print progress, the.tien.mai@fhi.no
#'
moewishart_em_cpp <- function(S_list, K = 2L, nu_in = NULL, max_em = 200L, max_nr = 50L, tol_em = 1e-8, verbose = TRUE) {
    .Call(`_moewishart_moewishart_em_cpp`, S_list, K, nu_in, max_em, max_nr, tol_em, verbose)
}

